name: alhazem
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_theme_switcher: ^2.0.10
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  connectivity_plus:
  dio: ^5.4.3+1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.4
  json_annotation: ^4.9.0
  multiple_result: ^5.1.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  dropdown_button2: ^2.3.9
  toastification: ^2.0.0
  number_pagination: ^1.0.7
  fast_cached_network_image: ^1.2.9
  intl: ^0.19.0
  flutter_barcode_listener: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: 
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    # - assets/jsons/

    
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
